### ISSUE TITLE
Unable to open the pcb with kicad

### ISSUE THREAD

**Issue by pascalorama** [stas2k/galspanic#1]
Hello there,

thanks for this project , i wanted to check the pcb , but i'm unable to open it with KiCad for windows,
Tried the latest version stable 5.1.7 , nightly build and a older version from May 2020. Do you have a link to the version you're using ? 

thanks in advance and best regards

![kicad](https://user-images.githubusercontent.com/25900414/98245661-8f3f7c00-1f71-11eb-953e-20eae4429e7a.png)

**Comment by stas2k** [comment]
You will have to use the dev version of kicad to open these. I do not know if ready made builds are available for Windows.

**Comment by stas2k** [comment]
I am going to close the issue as you can solve it by using a newer version
